image: Visual Studio 2017

# Temporarly fix for an issue for NuGet/AppVeyor connectivity;
# see appveyor.statuspage.io for more info. Should be removed when connectivty
# is restored.
init:
- ps: '[System.IO.File]::AppendAllText("C:\Windows\System32\drivers\etc\hosts", "`n93.184.221.200  api.nuget.org")'

before_build:
  - nuget restore
  - nuget restore iMobileDevice.Generator\packages.config -SolutionDirectory .
  - dotnet restore
  - if not exist ext mkdir ext
  - choco install -y wget
  - download.cmd

cache:
  - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - ext -> download.cmd
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'  # NuGet package for .NET Core

build_script:
  - msbuild iMobileDevice.Generator\iMobileDevice.Generator.csproj /p:Configuration=Debug /p:Platform=x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - iMobileDevice.Generator\bin\x86\Debug\iMobileDevice.Generator.exe . .\iMobileDevice-net
  - dotnet build imobiledevice-net\iMobileDevice-net.csproj
  - dotnet pack imobiledevice-net\iMobileDevice-net.csproj --version-suffix r%APPVEYOR_BUILD_NUMBER%

on_success:
  - ps: Push-AppVeyorArtifact imobiledevice-net\bin\Debug\imobiledevice-net.1.2.1-r$($env:APPVEYOR_BUILD_NUMBER).nupkg

nuget:
  project_feed: true
  account_feed: true